Fix front HSM interface
bmwcarit/MoCOCrW pull request #117
Opened 2022-08-08 07:07 UTC by johnfxgalea-e

Converts the HSMEngine class, which makes use of OpenSSL's ENGINE API to interact with HSMs, from an abstract to a concrete class. Virtual functions which cannot be implemented due to current lack of support (e.g., key storage) are removed for now.

Adds readPrivateKeyFromHSM() and readPublicKeyFromHSM() to the MoCOCrW inteface. Tests for loading keys are also included in this PR.

2022-08-08 08:29 UTC, wusto approved these changes
lgtm. Someone else should please have another look.

2022-08-08 08:30 UTC, garw requested changes
content-wise it looks good to me. just some nitpicks.
Do we already have integration tests against softhsm? I fear I lost the overview here…

2022-08-08 08:30 UTC, garw commented on tests/unit/CMakeLists.txt
> +    if(HSM_ENABLED)
Not sure why its split for the rest, but I think we should better group the directives per binary.

2022-08-08 08:30 UTC, garw commented on tests/unit/test_hsm.cpp
> +    std::string engineID = "engine_id";
Stick to one init style?

2022-08-09 07:28 UTC, johnfxgalea-e commented on tests/unit/test_hsm.cpp
> +    std::string engineID = "engine_id";
Done

2022-08-09 07:28 UTC, johnfxgalea-e commented on tests/unit/CMakeLists.txt
> +    if(HSM_ENABLED)
Let's punt this for now as that chance does not really concern this PR's Contribution.

2022-08-10 07:35 UTC, garw approved these changes

2022-08-10 08:54 UTC, merged