hsm: get RW session instead of creating it
bmwcarit/MoCOCrW pull request #146
Opened 2023-05-08 09:11 UTC by istepic

Due to engine_finish not being called on HsmEngine object destruction, sessions remain open. Approach to acquiring sessions before key generation is changed. If RW session already exists, a new one is not opened but reused. This approach is better irrespective of problems with engine_finish not being called.

2023-05-08 13:08 UTC, johnfxgalea-e requested changes
The general idea of the guard looks okay but it appears there is a race condition.

2023-05-08 13:08 UTC, johnfxgalea-e commented on dockerfiles/feature-support/hsm-patches/0001-Introduce-generic-keypair-generation-interface-and-e.patch
> ++	if (slot->rw_mode == 0) {
I think there is a race condition here

2023-05-08 13:10 UTC, johnfxgalea-e commented on dockerfiles/feature-support/hsm-patches/0001-Introduce-generic-keypair-generation-interface-and-e.patch
> ++	if (slot->rw_mode == 0) {
Also, can't rw also be -1? https://github.com/OpenSC/libp11/blob/281254bf3883ed17f4756243d78ac906342211d8/src/p11_slot.c#L427

2023-05-08 14:58 UTC, istepic commented on dockerfiles/feature-support/hsm-patches/0001-Introduce-generic-keypair-generation-interface-and-e.patch
> ++	if (slot->rw_mode == 0) {
> I think there is a race condition here

Can you clarify?

> Also, can't rw_mode also be -1 if not initialised? https://github.com/OpenSC/libp11/blob/281254bf3883ed17f4756243d78ac906342211d8/src/p11_slot.c#L427

True, done.

2023-05-09 10:22 UTC, johnfxgalea-e approved these changes

2023-05-09 10:25 UTC, johnfxgalea-e commented on dockerfiles/feature-support/hsm-patches/0001-Introduce-generic-keypair-generation-interface-and-e.patch
> ++	if (slot->rw_mode == 0) {
Discussed offline on thread safety guarantees (or lack there of by MoCOCrW).
See:
https://github.com/bmwcarit/MoCOCrW/blob/cc2acba5d6e55c94a144cb9306c9fb2345153911/README.md?plain=1#LL84C48-L84C90

2023-05-12 15:07 UTC, garw approved these changes

2023-05-12 15:07 UTC, garw approved these changes

2023-05-15 11:26 UTC, merged