Release 4.5.1
bmwcarit/MoCOCrW pull request #151
Opened 2023-09-11 08:49 UTC by istepic

2023-09-11 10:48 UTC, wusto approved these changes

2023-09-11 10:49 UTC, wusto requested changes

2023-09-11 10:49 UTC, wusto commented on CHANGELOG.md
> +of 12. This led to to successful but wrong encryption result.
```suggestion
of 12. This led to successful but wrong encryption result.
```

2023-09-11 13:04 UTC, wusto approved these changes

2023-09-12 08:19 UTC, cps-b approved these changes

2023-09-12 08:32 UTC, merged