Use Builder Pattern for HsmKeyParams
bmwcarit/MoCOCrW pull request #155
Opened 2023-10-30 08:56 UTC by cps-b

2023-10-30 16:07 UTC, garw requested changes

2023-10-30 16:07 UTC, garw commented on src/mococrw/hsm.h
> +    bool isExtractable() const { return cka_extractable; }
Do we really want to expose PKCS#11 slang here? Wouldn't it be better if this provides some Abstraction and we say here that the param is that the is is extractable or not? Sensitive is really not self-explanatory.

2023-10-30 16:07 UTC, garw commented on src/hsm.cpp
> +            HsmKeyParams::Builder().setCkaExtractable(false).setCkaSensitive(true).build();
Style: Most of the library uses {} for object construction.

2023-10-31 18:59 UTC, garw submitted a review, later dismissed
looks cleaner to me now. Feel free to merge after the consistency problem has been fixed.

2023-10-31 18:59 UTC, garw commented on src/mococrw/hsm.h
> +    bool extractable;
consistency: this lib prefixes private members with _

2023-11-10 15:03 UTC, cps-b commented
Merging in PR #156

2023-11-10 15:03 UTC, closed without merging